"""
Django settings for myopenstories project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from django.utils.translation import gettext_lazy as _
import django_heroku


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


#Adds translation for main page
LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'myopenstories/locale/'), #BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXX'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [ 'library.apps.LibraryConfig',
                   'accounts.apps.AccountsConfig',
                   'reader.apps.ReaderConfig',
                   'django.contrib.admin',
                   'django.contrib.auth', 'django.contrib.contenttypes',
                   'django.contrib.sessions', 'django.contrib.messages',
                   'django.contrib.staticfiles',
                   'crispy_forms',
                   'storages',
                   # Machina dependencies:
                   'mptt',
                   'haystack',
                   'widget_tweaks',
                   # Machina apps:
                   'machina',
                   'machina.apps.forum',
                   'machina.apps.forum_conversation',
                   'machina.apps.forum_conversation.forum_attachments',
                   'machina.apps.forum_conversation.forum_polls',
                   'machina.apps.forum_feeds',
                   'machina.apps.forum_moderation',
                   'machina.apps.forum_search',
                   'machina.apps.forum_tracking',
                   'machina.apps.forum_member',
                   'machina.apps.forum_permission',
                   #GDPR cookies
                   'cookielaw',
                   #Inline css in emails
                   'django_inlinecss',
                   #Email validation
                   'django_email_verification',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Machina
    'machina.apps.forum_permission.middleware.ForumPermissionMiddleware',
]

ROOT_URLCONF = 'myopenstories.urls'

from machina import MACHINA_MAIN_TEMPLATE_DIR
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),
                 os.path.join(BASE_DIR, 'myopenstories/templates'),
                 MACHINA_MAIN_TEMPLATE_DIR,
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'machina.core.context_processors.metadata',
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'myopenstories.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

#import dj_database_url
#DATABASES = {'default' : dj_database_url.config(conn_max_age=600, ssl_require=True)}#, default='sqlite://db.sqlite3')}



# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'accounts.User'

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGES = [
    ('en', _('English')),
    ('fr', _('French'))
]

LANGUAGE_CODE = 'en'

TIME_ZONE = 'Europe/Brussels'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

from machina import MACHINA_MAIN_STATIC_DIR
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    MACHINA_MAIN_STATIC_DIR,
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


EMAIL_HOST = 'in-v3.mailjet.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'XXXXXXXXXXXXXXXXXXXXXXXXXXX'
EMAIL_HOST_PASSWORD = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = "no-reply@mhios.com"
SERVER_EMAIL = "no-reply@mhios.com"

#EMAIL_HOST = 'smtp.sendgrid.net'
#EMAIL_PORT = 587
#EMAIL_HOST_USER = 'apikey'
#EMAIL_HOST_PASSWORD = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
#EMAIL_USE_TLS = True
#DEFAULT_FROM_EMAIL = 'XXXXXXXXXXXXXXXXXXXXXXXX'


#FOR EMAIL VALIDATION
EMAIL_ACTIVE_FIELD = 'is_active'
EMAIL_SERVER = EMAIL_HOST
EMAIL_ADDRESS = EMAIL_HOST_USER
EMAIL_FROM_ADDRESS = DEFAULT_FROM_EMAIL
EMAIL_PASSWORD = EMAIL_HOST_PASSWORD
EMAIL_MAIL_SUBJECT = 'Email validation - www.mhios.com'
EMAIL_MAIL_HTML = 'mail_body.html'
EMAIL_PAGE_TEMPLATE = 'confirm_template.html'
EMAIL_PAGE_DOMAIN = 'http://www.mhios.com/'



# Redirect to home URL after login (Default redirects to /accounts/profile/)
LOGIN_REDIRECT_URL = '/library'
LOGOUT_REDIRECT_URL = '/library'


CRISPY_TEMPLATE_PACK = 'bootstrap4'

#Using dropbox storage
DEFAULT_FILE_STORAGE = 'storages.backends.dropbox.DropBoxStorage'
DROPBOX_OAUTH2_TOKEN = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
DROPBOX_ROOT_PATH = '/app/media'

#To serve static files on server
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Activate Django-Heroku.
django_heroku.settings(locals())

#Heroku logs
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'ERROR'),
        },
    },
}


#Machina cache
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    },
    'machina_attachments': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': '/tmp',
    },
}

HAYSTACK_CONNECTIONS = {
    'default': {
        'ENGINE': 'haystack.backends.whoosh_backend.WhooshEngine',
        'PATH': os.path.join(BASE_DIR, 'whoosh_index'),
    },
}

MACHINA_DEFAULT_AUTHENTICATED_USER_FORUM_PERMISSIONS = [
    'can_see_forum',
    'can_read_forum',
    'can_start_new_topics',
    'can_reply_to_topics',
    'can_edit_own_posts',
    'can_post_without_approval',
    'can_vote_in_polls',
]

MACHINA_USER_DISPLAY_NAME_METHOD = 'get_nickname'
MACHINA_BASE_TEMPLATE_NAME = 'base_forum.html'
